# Generated by Django 4.0.6 on 2022-12-08 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='Faux', max_length=50, verbose_name='First Name')),
                ('l_name', models.CharField(default='Doe', max_length=50, verbose_name='Last Name')),
                ('number', models.IntegerField(default=0, verbose_name='Jersey Number')),
            ],
            options={
                'verbose_name_plural': 'Players',
                'db_table': 'Ballers',
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='players.players')),
                ('num_games', models.IntegerField()),
                ('tot_points', models.IntegerField(default=0)),
                ('ppg', models.FloatField(default=0, verbose_name='PPG')),
            ],
            options={
                'verbose_name_plural': 'Points',
                'db_table': 'Hoops',
            },
        ),
        migrations.CreateModel(
            name='Tweety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.CharField(max_length=100)),
                ('tweet_body', models.CharField(max_length=500)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
            ],
            options={
                'verbose_name_plural': 'Tweet',
            },
        ),
    ]
